### ISSUE TITLE
Make repository private

### ISSUE THREAD

**Issue by atn90** [luong-komorebi/Cache-Lab#1]
Can you take your repository down or make it private? Students are using it to cheat on the assignment by copying your code.

**Comment by luong-komorebi** [comment]
Hi there @atn90 
First of all, I am very sorry to hear that students are using this as a cheat for their assignments. I open this repo to :
1. Keep track of what I did learn in the past
2. Open it so that someone could take a look at my insight, particularly this file https://github.com/luong-komorebi/Cache-Lab/blob/master/Explanation%20for%20solution/1551020.pdf
I initially believe that my version is just one in many versions of this lab and no one could ever use this for cheating. Could you give me some opinions/ statistics on how students are using this to cheat? I would be happy close this right away if it is being used for bad purposes.

**Comment by atn90** [comment]
At least one student submitted your .c files verbatim while several others made cosmetic changes to make their solution appear different.

**Comment by luong-komorebi** [comment]
@atn90 I understood. I will change this to personal. I really hope that it would help you (although I dont think my source is the only one to deal with cache-lab).  To make sure that you see this message, please reply to this then I ll close the repo right away (please be aware that there are some forks which I am not confident whether will be turn private after I make this private)

**Comment by atn90** [comment]
Thank you. I will also reach out to other repositories as well. I also know one of the forks is one of the students in question.
